modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="ARR" #mandatory
credits="Credit to the people" #optional

[[mods]] #mandatory
modId="iljatech" #mandatory
version="1.19" #mandatory
displayName="IljaTech" #mandatory
authors = "ilja615"
description='''
My tech mod
'''

[[dependencies.iljatech]]
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.iljatech]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,)"
    ordering="NONE"
    side="BOTH"